# Generated by Django 5.2.9 on 2025-12-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='_processed',
            field=models.BooleanField(default=False),
        ),
    ]
